### ISSUE TITLE
Create statistics page

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/switchmap#61]
There is a need for a summary page. Not on the home page as this data could take time to calculate.

**Inventory (A)**

1. Model number
2. Number of devices

**Inventory (B)**

1. Device name
2. Model number

**Ports Summary Table**

1. Device
2. number of active ports
3. number of inactive ports
4. number of disabled ports
5. total across rows and columns

**Comment by arnavk1872** [comment]
hi, @palisadoes . Please assign this issue to me

**Comment by palisadoes** [comment]
We are focusing on talawa.
